Repository SamuelColeman/cinema-night, pull requests merged in 2019-10, with the labels that each got.

#6 Setup redux
  package-lock.json
  package.json
  src/Components/App/App.js
  src/actions/index.js
  src/index.js
  src/reducers/hasError.js
  src/reducers/index.js
  src/reducers/isLoading.js
  src/reducers/movies.js
Labels: enhancement

#8 Add poster display to movie card
  package-lock.json
  package.json
  src/apiCalls.js
Labels: enhancement

#10 Login existing user works!
  src/Components/App/App.js
  src/Components/Form/Form.js
  src/actions/index.js
  src/apiCalls.js
  src/index.js
  src/reducers/currentUser.js
  src/reducers/index.js
Labels: enhancement

#11 Sign up
  src/Components/Form/Form.js
  src/Components/MoviesContainer/MoviesContainer.js
  src/actions/index.js
  src/apiCalls.js
  src/reducers/index.js
  src/reducers/signUp.js
Labels: enhancement

#12 Add basic routing and refactor movie container to use global state
  src/Components/App/App.js
  src/Components/Form/Form.js
  src/Components/MoviesContainer/MoviesContainer.js
Labels: enhancement

#14 Sort favourite
  src/Components/App/App.js
  src/Components/MovieCard/MovieCard.js
  src/Components/MovieCard/__snapshots__/MovieCard.test.js.snap
  src/Components/MoviesContainer/MoviesContainer.js
  src/Components/MoviesContainer/__snapshots__/MoviesContainer.test.js.snap
  src/actions/index.js
  src/reducers/currentUser.js
  src/reducers/index.js
  src/reducers/isFavourite.js
Labels: bug, help wanted

#18 Add error handling for favorite button if no current user
  src/Components/App/App.js
  src/Components/Form/Form.js
  src/Components/MovieCard/MovieCard.js
  src/Components/MoviesContainer/MoviesContainer.js
Labels: enhancement

#22 Add basic functionality for displaying movie in new route on card click
  src/Components/App/App.js
  src/Components/MovieCard/MovieCard.css
  src/Components/MovieCard/MovieCard.js
  src/Components/MoviePage/MoviePage.css
  src/Components/MoviePage/MoviePage.js
  src/Components/MoviePage/MoviePage.test.js
  src/apiCalls.js
Labels: enhancement

#32 Fetch errors
  src/Containers/App/App.js
  src/apiCalls.js
Labels: bug, enhancement
